name: Planetoids
main: org.canis85.planetoidgen.PlanetoidGen
version: 1.3.0
description: Creates a world full of planets.
author: Canis85
commands:
    pltp:
        description: Moves the player to/from the planetoids area
        usage: /pltp
