name: Planetoids
main: org.canis85.planetoidgen.PlanetoidGen
version: 1.2.2
description: Creates a world full of planets.
author: Canis85
commands:
    pltp:
        description: Moves the player to the planetoids area
        usage: /pltp
